// Mock ISQ Agent run data — Sunflowers Charity questionnaire
// Faithful to plan-03 (data shape) + plan-08 (confidence + flagging)

window.ISQ_RUN = {
  meta: {
    run_id: "sun-20260525-001",
    filename: "Sunflowers_Charity_Supplier_ISQ_Questionnaire.pdf",
    origin: "Sunflowers Charity",
    received_at: "2026-05-25T19:30:00Z",
    completed_at: "2026-05-25T19:30:42Z",
    total_questions: 20,
  },
  summary: {
    total_questions: 20,
    flagged_count: 2,
    flagged_indices: [6, 11],
    total_cost_usd: 0.078,
    total_tokens_in: 26340,
    total_tokens_out: 2060,
    total_latency_ms: 42180,
    average_confidence: 0.86,
    banner: null,
  },
  answers: [
    {
      index: 1,
      question: "Do you maintain a formal Information Security Policy?",
      answer: "Yes. Northstar Labs maintains a formal Information Security Policy which is reviewed annually and approved by senior leadership. The policy covers access control, encryption, acceptable use, security responsibilities, asset management, and incident management.",
      citations: [
        { id: "ISP §1", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 1 },
        { id: "ISQ_01 Q1", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 1 },
      ],
      confidence: { score: 0.93, cites_policy: 1.0, on_topic: 0.95, vendor_tone: 0.90, complete: 0.80 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1240, tokens_out: 95, cost_usd: 0.0042, latency_ms: 1820 },
    },
    {
      index: 2,
      question: "Is multi-factor authentication (MFA) enforced for staff access to business systems?",
      answer: "Yes. MFA is enforced for all staff accessing business systems including email, source control, cloud infrastructure, and internal applications. Hardware keys are issued to engineers; TOTP is the default for all other staff.",
      citations: [
        { id: "ISP §4.2", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 4 },
        { id: "ISQ_01 Q4", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 2 },
      ],
      confidence: { score: 0.91, cites_policy: 1.0, on_topic: 0.95, vendor_tone: 0.85, complete: 0.80 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1280, tokens_out: 78, cost_usd: 0.0039, latency_ms: 1640 },
    },
    {
      index: 3,
      question: "How frequently are staff awareness training sessions conducted?",
      answer: "Information security awareness training is mandatory for all new starters within their first two weeks and is repeated annually for all staff. Phishing simulations are run quarterly with targeted follow-up training for any staff who interact with simulated phishing messages.",
      citations: [
        { id: "ISP §6.1", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 6 },
      ],
      confidence: { score: 0.88, cites_policy: 0.95, on_topic: 0.90, vendor_tone: 0.85, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1190, tokens_out: 88, cost_usd: 0.0041, latency_ms: 1720 },
    },
    {
      index: 4,
      question: "Do you encrypt customer data at rest and in transit?",
      answer: "All customer data is encrypted at rest using AES-256 and in transit using TLS 1.3. Encryption keys are managed via the cloud provider's managed KMS with quarterly rotation. No customer data is stored unencrypted at any point in the lifecycle.",
      citations: [
        { id: "ISP §7.3", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 7 },
        { id: "ISQ_01 Q8", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 3 },
        { id: "ISQ_02 Q6", source: "Northstar_Labs_Previous_ISQ_Completed_02.pdf", page: 2 },
      ],
      confidence: { score: 0.95, cites_policy: 1.0, on_topic: 1.0, vendor_tone: 0.90, complete: 0.85 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1330, tokens_out: 91, cost_usd: 0.0044, latency_ms: 1810 },
    },
    {
      index: 5,
      question: "Are penetration tests conducted on customer-facing systems, and how often?",
      answer: "External penetration tests are conducted annually by a CREST-accredited third party. Internal vulnerability scans run weekly across all customer-facing systems. The most recent external test was completed in Q1 2026; findings and remediation evidence are available under NDA.",
      citations: [
        { id: "ISP §8.4", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 8 },
        { id: "ISQ_01 Q12", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 3 },
      ],
      confidence: { score: 0.89, cites_policy: 1.0, on_topic: 0.90, vendor_tone: 0.85, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1310, tokens_out: 102, cost_usd: 0.0046, latency_ms: 1880 },
    },
    {
      index: 6,
      question: "How is privileged access to operational technology (OT) controlled?",
      answer: "Northstar Labs does not operate operational technology (OT) systems. Our services are software-only — cloud-hosted applications and AI engineering work. Privileged access to our software development and production environments is controlled via short-lived credentials, just-in-time access via SSO, and full audit logging.",
      citations: [
        { id: "ISP §5.2", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 5 },
      ],
      confidence: { score: 0.55, cites_policy: 0.60, on_topic: 0.50, vendor_tone: 0.85, complete: 0.40 },
      needs_review: true,
      review_reason: "LLM flagged: Question asks specifically about operational technology. Northstar Labs is software-only. Answer represents a scope-limitation statement.",
      metrics: { tokens_in: 1180, tokens_out: 124, cost_usd: 0.0051, latency_ms: 2140 },
    },
    {
      index: 7,
      question: "Do you have a documented incident response plan?",
      answer: "Yes. Northstar Labs maintains a documented Incident Response Plan covering identification, containment, eradication, recovery, and post-incident review. The plan is reviewed annually and tested via tabletop exercises twice per year. The Information Security Lead is the named incident commander.",
      citations: [
        { id: "ISP §9.1", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 9 },
        { id: "ISQ_01 Q15", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 4 },
      ],
      confidence: { score: 0.92, cites_policy: 1.0, on_topic: 0.95, vendor_tone: 0.90, complete: 0.80 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1220, tokens_out: 102, cost_usd: 0.0044, latency_ms: 1750 },
    },
    {
      index: 8,
      question: "What is your maximum acceptable time to notify customers of a confirmed data breach?",
      answer: "Northstar Labs commits to notifying affected customers of a confirmed personal data breach within 72 hours of confirmation, in line with UK GDPR. Notification includes a description of the breach, categories and approximate number of data subjects affected, likely consequences, and the measures being taken to address it.",
      citations: [
        { id: "ISP §9.3", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 9 },
        { id: "ISQ_02 Q11", source: "Northstar_Labs_Previous_ISQ_Completed_02.pdf", page: 3 },
      ],
      confidence: { score: 0.90, cites_policy: 0.95, on_topic: 1.0, vendor_tone: 0.85, complete: 0.80 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1290, tokens_out: 116, cost_usd: 0.0049, latency_ms: 1900 },
    },
    {
      index: 9,
      question: "How are third-party suppliers and sub-processors assessed?",
      answer: "Third-party suppliers and sub-processors are assessed via a structured due-diligence questionnaire covering security, data handling, and certifications. Critical suppliers are reviewed annually. A current list of sub-processors is maintained and available to customers on request under NDA.",
      citations: [
        { id: "ISP §11.2", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 11 },
      ],
      confidence: { score: 0.84, cites_policy: 0.85, on_topic: 0.90, vendor_tone: 0.80, complete: 0.80 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1170, tokens_out: 89, cost_usd: 0.0040, latency_ms: 1680 },
    },
    {
      index: 10,
      question: "Where is customer data physically stored?",
      answer: "Customer data is stored in UK and EU data centres operated by our cloud provider. Production data does not leave the UK/EU region under normal operation. Disaster-recovery replicas are maintained within the same legal jurisdiction.",
      citations: [
        { id: "ISP §7.5", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 7 },
        { id: "ISQ_01 Q19", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 5 },
      ],
      confidence: { score: 0.87, cites_policy: 0.95, on_topic: 0.90, vendor_tone: 0.80, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1210, tokens_out: 81, cost_usd: 0.0041, latency_ms: 1700 },
    },
    {
      index: 11,
      question: "What are your Recovery Time Objective (RTO) and Recovery Point Objective (RPO) for critical SCADA-connected services?",
      answer: "Northstar Labs does not operate SCADA-connected services. Our offering is cloud-hosted software with no industrial control system integration. For our cloud platform, RTO is 4 hours and RPO is 1 hour. We can provide tailored figures for non-SCADA scenarios on request.",
      citations: [
        { id: "ISP §10.1", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 10 },
      ],
      confidence: { score: 0.51, cites_policy: 0.55, on_topic: 0.45, vendor_tone: 0.80, complete: 0.40 },
      needs_review: true,
      review_reason: "LLM flagged: Question is SCADA-specific. Northstar Labs is software-only and does not operate SCADA-connected services. Answer represents a scope-limitation statement; figures provided are for the equivalent cloud-platform service.",
      metrics: { tokens_in: 1240, tokens_out: 134, cost_usd: 0.0054, latency_ms: 2230 },
    },
    {
      index: 12,
      question: "Do you maintain audit logs for privileged actions, and how long are they retained?",
      answer: "Audit logs for privileged actions are maintained for all production systems with a minimum retention period of 12 months. Logs are immutable, centrally aggregated, and reviewed by the Information Security Lead weekly. Tamper-evident storage is used.",
      citations: [
        { id: "ISP §8.6", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 8 },
        { id: "ISQ_02 Q14", source: "Northstar_Labs_Previous_ISQ_Completed_02.pdf", page: 4 },
      ],
      confidence: { score: 0.89, cites_policy: 1.0, on_topic: 0.90, vendor_tone: 0.85, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1260, tokens_out: 92, cost_usd: 0.0043, latency_ms: 1770 },
    },
    {
      index: 13,
      question: "Do staff sign a confidentiality agreement before accessing customer data?",
      answer: "Yes. All staff sign a confidentiality and data protection agreement as part of their employment contract before accessing any customer data. Contractors sign an equivalent agreement before being granted access.",
      citations: [
        { id: "ISP §3.4", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 3 },
      ],
      confidence: { score: 0.86, cites_policy: 0.95, on_topic: 0.90, vendor_tone: 0.80, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1150, tokens_out: 72, cost_usd: 0.0037, latency_ms: 1590 },
    },
    {
      index: 14,
      question: "How are vulnerabilities in dependencies identified and remediated?",
      answer: "Dependency vulnerabilities are identified via automated scanning on every commit and on a daily schedule. Critical severity issues are remediated within 7 days; high severity within 30 days. The dependency policy and SLA are published internally.",
      citations: [
        { id: "ISP §8.2", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 8 },
        { id: "ISQ_01 Q17", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 4 },
      ],
      confidence: { score: 0.85, cites_policy: 0.90, on_topic: 0.90, vendor_tone: 0.80, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1220, tokens_out: 87, cost_usd: 0.0041, latency_ms: 1730 },
    },
    {
      index: 15,
      question: "Is there a documented data retention and disposal policy?",
      answer: "Yes. Northstar Labs maintains a documented Data Retention and Disposal Policy. Customer data is retained for the duration of the contract and for a defined post-termination period before secure deletion. Disposal evidence is logged.",
      citations: [
        { id: "ISP §7.8", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 7 },
      ],
      confidence: { score: 0.83, cites_policy: 0.90, on_topic: 0.85, vendor_tone: 0.80, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1180, tokens_out: 78, cost_usd: 0.0038, latency_ms: 1620 },
    },
    {
      index: 16,
      question: "Do you have cyber insurance, and what is the coverage limit?",
      answer: "Northstar Labs maintains cyber insurance with a coverage limit appropriate to the scale of customer engagements. Specific policy limits and certificates of insurance are available to customers under NDA on request.",
      citations: [
        { id: "ISQ_02 Q21", source: "Northstar_Labs_Previous_ISQ_Completed_02.pdf", page: 5 },
      ],
      confidence: { score: 0.78, cites_policy: 0.75, on_topic: 0.85, vendor_tone: 0.80, complete: 0.65 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1130, tokens_out: 70, cost_usd: 0.0036, latency_ms: 1580 },
    },
    {
      index: 17,
      question: "Are background checks performed on staff with access to customer data?",
      answer: "Yes. All staff with access to customer data undergo background checks proportionate to the sensitivity of their role, including identity verification, right-to-work checks, and where appropriate criminal record checks. Checks are repeated for role changes.",
      citations: [
        { id: "ISP §3.2", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 3 },
      ],
      confidence: { score: 0.85, cites_policy: 0.90, on_topic: 0.90, vendor_tone: 0.80, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1180, tokens_out: 82, cost_usd: 0.0039, latency_ms: 1650 },
    },
    {
      index: 18,
      question: "What is the process for revoking access when staff leave?",
      answer: "On termination, access to all systems is revoked within one business hour of the effective end date via the central identity provider. Devices are recovered, encryption keys rotated, and the offboarding checklist is signed off by the Information Security Lead.",
      citations: [
        { id: "ISP §5.5", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 5 },
        { id: "ISQ_01 Q22", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 5 },
      ],
      confidence: { score: 0.88, cites_policy: 0.95, on_topic: 0.90, vendor_tone: 0.85, complete: 0.80 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1220, tokens_out: 89, cost_usd: 0.0042, latency_ms: 1740 },
    },
    {
      index: 19,
      question: "Do you maintain audit logs sufficient to support forensic investigation?",
      answer: "Yes. Audit logs across application, infrastructure, and access events are centrally aggregated with sufficient detail and retention to support forensic investigation. Logs are protected against tampering and segregated from operational access.",
      citations: [
        { id: "ISP §8.6", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 8 },
        { id: "ISQ_02 Q14", source: "Northstar_Labs_Previous_ISQ_Completed_02.pdf", page: 4 },
      ],
      confidence: { score: 0.87, cites_policy: 0.95, on_topic: 0.90, vendor_tone: 0.85, complete: 0.75 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1240, tokens_out: 84, cost_usd: 0.0040, latency_ms: 1690 },
    },
    {
      index: 20,
      question: "Please provide details of any relevant certifications or compliance frameworks followed by your organisation.",
      answer: "Northstar Labs aligns its information security programme with the ISO 27001 framework. Cyber Essentials Plus certification is held and renewed annually. The internal control framework is mapped to NIST CSF for operational reference.",
      citations: [
        { id: "ISP §1.4", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 1 },
        { id: "ISQ_01 Q24", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 6 },
        { id: "ISQ_02 Q23", source: "Northstar_Labs_Previous_ISQ_Completed_02.pdf", page: 5 },
      ],
      confidence: { score: 0.90, cites_policy: 1.0, on_topic: 0.95, vendor_tone: 0.85, complete: 0.80 },
      needs_review: false, review_reason: null,
      metrics: { tokens_in: 1300, tokens_out: 78, cost_usd: 0.0040, latency_ms: 1660 },
    },
  ],
  top_citations: [
    { id: "ISP §1", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 1, used_in: 2, avg_score: 0.89 },
    { id: "ISP §4.2", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 4, used_in: 1, avg_score: 0.91 },
    { id: "ISP §7.3", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 7, used_in: 2, avg_score: 0.93 },
    { id: "ISP §8.6", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 8, used_in: 2, avg_score: 0.88 },
    { id: "ISP §9.1", source: "Northstar_Labs_Information_Security_Policy.pdf", page: 9, used_in: 1, avg_score: 0.90 },
    { id: "ISQ_01 Q1", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 1, used_in: 1, avg_score: 0.85 },
    { id: "ISQ_01 Q12", source: "Northstar_Labs_Previous_ISQ_Completed_01.pdf", page: 3, used_in: 1, avg_score: 0.84 },
    { id: "ISQ_02 Q11", source: "Northstar_Labs_Previous_ISQ_Completed_02.pdf", page: 3, used_in: 1, avg_score: 0.86 },
  ],
  stages: [
    { id: "embed",  label: "Embed", count: 20, latency_ms: 4720 },
    { id: "search", label: "Vector search", count: 20, latency_ms: 2620 },
    { id: "generate", label: "Generate (Claude Sonnet 4.5)", count: 20, latency_ms: 31180 },
    { id: "confidence", label: "Confidence aggregation", count: 20, latency_ms: 60 },
  ],
};

// Other example questionnaires for upload-history affordance (not deeply used)
window.ISQ_EXAMPLES = [
  { name: "Blackridge_Wind_Energy_ISQ.pdf", size: "8.2 MB", origin: "Blackridge Wind Energy" },
  { name: "Simple_Salvage_Vendor_Questionnaire.xlsx", size: "112 KB", origin: "Simple Salvage" },
];
